---
title: "R Notebook"
output: html_notebook
---

# Principle Component Analysis in R 

```{r}
# Loading required package: psych
require(psych)

# Loading required package: GPArotation
require(GPArotation)

library(lattice)
url <- "/Users/jialincheoh/Desktop/survey_final_read.csv"
survey <- read.csv(url, header=TRUE)
survey
```

```{r}
names(survey)[1:13] <- c("monetary_compensation", "excellent_programmer", "internship", 
                         "introduce_ideas", "get_in_touch", "known_creativity", "improve_skills", 
                         "test_capability", "enjoy_problems", "keep_up", "dissatisfaction", "curious", "pass_class")
survey
```

```{r}
# Extract all 13 survey items with motivation construct
motivation <- survey[c(1:13)]
motivation
```


```{r}
lowerCor(motivation)
```
```{r}
library(correlation)

correlation::correlation(motivation,
                         include_factors = TRUE, method = "auto"
)
```

```{r}
# Do the PCA with singular value decomposition of the (centered and possibly scaled) data matrix

my.prc = prcomp(motivation, center=TRUE, scale=TRUE)
screeplot(my.prc, main="Scree Plot", xlab="Components")
screeplot(my.prc, main="Scree Plot", type="line" )
```
```{r}
my.prc
```

```{r}
# Kaiser criterion to determine the number of principle components to keep 
my.prc$sdev ^ 2
```

```{r}

screeplot(my.prc, main="Scree Plot", xlab="Components")
```
```{r}
# DotPlot PC1

load    <- my.prc$rotation
sorted.loadings <- load[order(load[, 1]), 1]
myTitle <- "Loadings Plot for PC1" 
myXlab  <- "Variable Loadings"
dotplot(sorted.loadings, main=myTitle, xlab=myXlab, cex=1.5, col="red")
summary(my.prc)
```

```{r}
# DotPlot PC2

sorted.loadings <- load[order(load[, 2]), 2]
myTitle <- "Loadings Plot for PC2"
myXlab  <- "Variable Loadings"
dotplot(sorted.loadings, main=myTitle, xlab=myXlab, cex=1.5, col="red")
```
```{r}
# Now draw the BiPlot
biplot(my.prc, cex=c(1, 0.7))
```
```{r}
my.prc$rotation[, 1:2]
```
```{r}
options(max.print=1000000)
project.b = predict(my.prc, motivation)
project.b
```



```{r}
# Apply the Varimax Rotation
my.var <- varimax(my.prc$rotation[, 1:6])

my.var
```
## Interpretation: 

> Assume threshold 0.5 

> PC1 - Gain Knowledge and Intrinsic Innovation Interest ( only missed enjoy_problems )
> PC2 - Dissatisfaction 
> PC3 - Monetary rewards 
> PC4 - Curious 
> PC5 - Get known for excellent programmer / excellent creativity 
> PC6 - Show Ideas


```{r}
# Apply the Varimax Rotation
my.var <- varimax(my.prc$rotation[, 1:2])

my.var
```

```{r}
# Apply the Varimax Rotation
my.var <- varimax(my.prc$rotation[, 1:3])

my.var
```
```{r}
head(my.prc$x)
```

```{r}
summary(my.prc)
```

```{r}
pca <- predict(my.prc, newdata=motivation)
pca
```
```{r}
dim(motivation)
```

```{r}
View(motivation)
```

```{r}
print(my.prc)
```
```{r}
summary(motivation)
```

```{r}
predict(motivation, newdata=tail(motivation, 2))
```


```{r}
head(my.prc$x)
```

```{r}
pca_frame <- as.data.frame(pca)
pca_frame
```

```{r}
allData <- cbind(pca_frame[1], id = survey$hack_id)
allData
```
```{r}
allData_abs <- abs(allData)
allData_abs
```
```{r}
anova_1 <- as.data.frame(allData_abs)
anova_1
```

```{r}
ANOVA_RESULTS_1 <- aov(PC1 ~ id, data=anova_1)
summary(ANOVA_RESULTS_1)
```

```{r}
allData_PC2 <- cbind(pca_frame[2], id = survey$hack_id)
allData_PC2
```

```{r}
allData_abs_PC2 <- abs(allData_PC2)
allData_abs_PC2
```
 
```{r}
anova_2 <- as.data.frame(allData_abs_PC2)
anova_2
```
 
```{r}
ANOVA_RESULTS_2 <- aov(PC2 ~ id, data=anova_2)
summary(ANOVA_RESULTS_2)
```
 
 