---
title: "R Notebook"
output: html_notebook
---


```{r}
df<-read.csv("input/commits.csv", header =TRUE, sep=",")
df
```

```{r}
df$count <- log(df$count+1) 
```


```{r}
# standardizing variables for skills and aspirations. 
cols <- c("log_count")
df[cols] <- scale(df[cols])
```


```{r}
mod <- lm(count ~ factor(Group), data = df)
summary(mod)
```
```{r}
# convert to nominal factor
df$Group = factor(df$Group)
df$phase = factor(df$phase)
```

```{r}
library(plyr)
ddply(df, ~ Group * phase, function(data) summary(data$count) )
ddply(df, ~ Group * phase, summarise, count.mean=mean(count), count.sd = sd(count))
```
```{r}
# histograms for two factors
hist(df[df$Group == 0 & df$phase == 1,]$count )
hist(df[df$Group == 0 & df$phase == 2,]$count )
hist(df[df$Group == 0 & df$phase == 3,]$count )
hist(df[df$Group == 0 & df$phase == 4,]$count )
hist(df[df$Group == 0 & df$phase == 5,]$count )
hist(df[df$Group == 1 & df$phase == 1,]$count )
hist(df[df$Group == 1 & df$phase == 2,]$count )
hist(df[df$Group == 1 & df$phase == 3,]$count )
hist(df[df$Group == 1 & df$phase == 4,]$count )
hist(df[df$Group == 1 & df$phase == 5,]$count )
hist(df[df$Group == 2 & df$phase == 1,]$count )
hist(df[df$Group == 2 & df$phase == 2,]$count )
hist(df[df$Group == 2 & df$phase == 3,]$count )
hist(df[df$Group == 2 & df$phase == 4,]$count )
hist(df[df$Group == 2 & df$phase == 5,]$count )
hist(df[df$Group == 3 & df$phase == 1,]$count )
hist(df[df$Group == 3 & df$phase == 2,]$count )
hist(df[df$Group == 3 & df$phase == 3,]$count )
hist(df[df$Group == 3 & df$phase == 4,]$count )
hist(df[df$Group == 3 & df$phase == 5,]$count )
boxplot(count ~ Group * phase, data = df, xlab="Group.phase", ylab="count")
with(df, interaction.plot(Group, phase, count, ylim=c(0, max(count)))) # interaction plot
```

```{r}
# library for LMM we will use on relational novelty 

library(lme4)
library(lmerTest)
library(car)
```

```{r}
contrasts(df$Group) <= "contr.sum"
contrasts(df$phase) <= "contr.sum"
```
```{r}
full.model = lmer( count ~ Group/phase + (1 | Student), data = df, REML = FALSE)
Anova(full.model, type=3, test.statistics="F")
full.model
```
```{r}

```

