---
title: "R Notebook"
output: html_notebook
---

```{r}
# reading input 
df<-read.csv("input/rare5.csv", header =TRUE, sep=",")
#df <- df[complete.cases(df), ]  
df
```
```{r}
df <- subset(df, len_match5 > 0)
df
```



```{r}
df$Group = factor(df$Group)
df$phase = factor(df$phase)
```

```{r}
df$log_len_match5 <- log(df$len_match5+1) 
df$log_count <- log(df$count+1) 
df$Q7_Q7_1 <- log(df$Q7_Q7_1+1)
df$Q7_Q7_2 <- log(df$Q7_Q7_2+1)
df$Q8_Q8_1 <- log(df$Q8_Q8_1+1)
df$Q10 <- log(df$Q10+1)
df
```

```{r}
cols <- c( "log_len_match5")
df[cols] <- scale(df[cols])
df
```

```{r}
library(lme4)
mod1 <- lmer(log_len_match5 ~ Group + ( 1 | phase), data = df, REML = FALSE )
summary(mod1)
```

```{r}
table <- aov(len_match5 ~ Group, data = df)
summary(table)
```

```{r}
forplot <- TukeyHSD(table, which = 'Group')
plot(forplot)
```

```{r}
TukeyHSD(table, which = 'Group')
```
```{r}
tableb <- aov(len_match5 ~ Group + log_count + Q7_Q7_1 + Q7_Q7_2 + Q8_Q8_1 + Q10, data = df)
summary(tableb)
```

```{r}
TukeyHSD(tableb, which = 'Group')
```

