---
title: "R Notebook"
output: html_notebook
---

```{r}
df <- read.csv("input/template.csv", header =TRUE, sep=",")
df <- df[complete.cases(df), ] # Apply complete.cases function
df
```
```{r}
# convert to nominal factor
df$phase = factor(df$phase)
df$group = factor(df$group)
```

```{r}
contrasts(df$group) <- "contr.sum"
contrasts(df$phase) <- "contr.sum"
```

```{r}
# create new columns called log exploration
df$log_template_similarity <- log(df$similarity+1) 
df$log_count <- log(df$count+1) 
df$Q7_Q7_1<- log(df$Q7_Q7_1+1)
df$Q7_Q7_2<- log(df$Q7_Q7_2+1)
df$Q8_Q8_1<- log(df$Q8_Q8_1+1)
df$Q10<- log(df$Q10+1)
df
```


```{r}
df
```

```{r}
library(lme4)
mod1 <- lm(log_template_similarity ~ group + log_count+ Q7_Q7_1 + Q7_Q7_2 + Q8_Q8_1 + Q10, data=df)
summary(mod1)
```
```{r}
table <- aov(log_template_similarity ~ Q7_Q7_1 + Q7_Q7_2 + Q8_Q8_1 + Q10 + log_count + group, data = df)
summary(table)
```

```{r}
forplot <- TukeyHSD(table, which = 'group')
plot(forplot)
```
```{r}
TukeyHSD(table, which = 'group')
```

