---
title: "R Notebook"
output: html_notebook
---

# All Phases and All Groups 

```{r}
df<-read.csv("/Users/jialincheoh/Library/CloudStorage/Box-Box/NSF IronHacks App 2016 - 2019/05 Experiments 2017/01 Hack Spring 2017/01 Summary Spring 2017/02 Data/processed-data/remove_na_overall.csv", header =TRUE, sep=",")
df[is.na(df)] <- 0
log_y <- log10(df$len_match + 1)
log_y
```

```{r}
quantile(df$len_match, 0.2)
```

```{r}
for (x in 0.05:1:0.05){
  quantile(log_y, 0.2)
}
```


```{r}
#create histogram for original distribution
hist(df0$len_match, col='steelblue', main='Original')
```
```{r}
hist(log_y, col='coral2', main='Log Transformed')
```


# Top 10% Rare Functions [ OVERALL CASE ]

```{r}
df0 <- df[df$Group == 0, ] 
df0[is.na(df0)] <- 0
```

```{r}
#log_y <- log10(complete$len_match)
#create histogram for original distribution
#hist(log_y, col='steelblue', main='Original')
log_y <- log10(df0$len_match + 1)
log_y
```

```{r}
#create histogram for original distribution
hist(df0$len_match, col='steelblue', main='Original')
```


```{r}
hist(log_y, col='coral2', main='Log Transformed')
```
```{r}
shapiro.test(log_y)
```

```{r}
df1 <- df[df$Group == 1, ] 
df1[is.na(df1)] <- 0
log_y <- log10(df1$len_match + 1)
log_y
```

```{r}
#create histogram for original distribution
hist(df1$len_match, col='steelblue', main='Original')
```
```{r}
hist(log_y, col='coral2', main='Log Transformed')
```
```{r}
shapiro.test(log_y)
```

```{r}
df2 <- df[df$Group == 2, ] 
df2[is.na(df2)] <- 0
log_y <- log10(df2$len_match + 1)
log_y
```

```{r}
#create histogram for original distribution
hist(df2$len_match, col='steelblue', main='Original')
```

```{r}
hist(log_y, col='coral2', main='Log Transformed')
```
```{r}
shapiro.test(log_y)
```

```{r}
df3 <- df[df$Group == 3, ] 
df3[is.na(df3)] <- 0
log_y <- log10(remove$len_match)
log_y
```
```{r}
#create histogram for original distribution
hist(remove$len_match, col='steelblue', main='Original')
```
```{r}
hist(log_y, col='coral2', main='Log Transformed')
```
```{r}
shapiro.test(remove$len_match)
```


```{r}
shapiro.test(log_y)
```

# Non-Repetitive Functions [ OVERALL CASE ]
```{r}
df<-read.csv("/Users/jialincheoh/Library/CloudStorage/Box-Box/NSF IronHacks App 2016 - 2019/05 Experiments 2017/01 Hack Spring 2017/01 Summary Spring 2017/02 Data/processed-data/overall-2.csv", header =TRUE, sep=",")
df0 <- df[df$Group == 0, ] 
df0
```

```{r}
remove <- df0[df0$len_unique != 0, ]
removed <- remove[!is.na(remove$len_unique), ]
#log_y <- log10(complete$len_match)
#create histogram for original distribution
#hist(log_y, col='steelblue', main='Original')
log_y <- log10(removed$len_unique)
log_y
```
```{r}
#create histogram for original distribution
hist(removed$len_unique, col='steelblue', main='Original')
```
```{r}
hist(log_y, col='coral2', main='Log Transformed')
```
```{r}
shapiro.test(removed$len_unique)
```


```{r}
shapiro.test(log_y)
```

```{r}
df1 <- df[df$Group == 1, ] 
remove <- df1[df1$len_unique != 0, ]
removed <- remove[!is.na(remove$len_unique), ]
log_y <- log10(removed$len_unique)
log_y
```
```{r}
#create histogram for original distribution
hist(removed$len_unique, col='steelblue', main='Original')
```
```{r}
hist(log_y, col='coral2', main='Log Transformed')
```
```{r}
shapiro.test(log_y)
```

```{r}
df2 <- df[df$Group == 2, ] 
remove <- df2[df2$len_unique != 0, ]
removed <- remove[!is.na(remove$len_unique), ]
log_y <- log10(removed$len_unique)
log_y
```
```{r}
#create histogram for original distribution
hist(removed$len_unique, col='steelblue', main='Original')
```
```{r}
hist(log_y, col='coral2', main='Log Transformed')
```
```{r}
shapiro.test(log_y)
```

```{r}
df3 <- df[df$Group == 3, ] 
remove <- df3[df3$len_unique != 0, ]
removed <- remove[!is.na(remove$len_unique), ]
log_y <- log10(removed$len_unique)
log_y
```
```{r}
#create histogram for original distribution
hist(removed$len_unique, col='steelblue', main='Original')
```
```{r}
hist(log_y, col='coral2', main='Log Transformed')
```
```{r}
shapiro.test(log_y)
```

