---
title: "R Notebook"
output: html_notebook
---


```{r}
# reading input 
df <- read.csv("novelty_complete_rev.csv", header =TRUE, sep=",")
#df <- df[complete.cases(df), ]  
df
```

```{r}
df$ln_novelty <- log(df$novelty+1) 
df$ln_abs_perform_diff_best <- log(df$abs_perform_diff_best+1) 
df$group = factor(df$group)
df
```


```{r}
df$group <- relevel(df$group, ref = "3")
mod <- lm(ln_novelty ~ factor(group), data=df)
summary(mod)
```
```{r}
mod <- lm(ln_abs_perform_diff_best ~ factor(group), data=df)
summary(mod)
```


```{r}
with(df, interaction.plot(group, phase, ln_novelty, ylim=c(0, max(ln_novelty)))) # interaction plot
```

```{r}
with(df, interaction.plot(group, phase, ln_abs_perform_diff_best, ylim=c(0, max(ln_abs_perform_diff_best)))) # interaction plot
```

```{r}
df$group <- relevel(df$group, ref = "3")
mod2 <- lm(ln_novelty ~ factor(group) + abs_perform_diff_best + Q7_Q7_1 + Q7_Q7_2 + Q8_Q8_1 + Q10, data=df)
summary(mod2)
```

```{r}
## check multicollinearity between variables 
install.packages("car")
library(car)

car::vif(mod2)
```

