---
title: "R Notebook"
output: html_notebook
---


```{r}
df<-read.csv("novelty.csv", header =TRUE, sep=",")
df
```

```{r}
df$log_relational_novelty <- log(df$similarity+1) 
df
```


```{r}
# standardizing variables
cols <- c("Q7_Q7_1", "Q7_Q7_2", "Q8_Q8_1", "Q10", "log_relational_novelty")
df[cols] <- scale(df[cols])
df
```



```{r}
mod <- lm( log_relational_novelty ~ Q10 + Q8_Q8_1 + Q7_Q7_1 + Q7_Q7_2, data = df)
summary(mod)
```

```{r}
mod <- lm( log_relational_novelty ~ factor(group) , data = df)
summary(mod)
```

```{r}
mod <- lm( log_relational_novelty ~ factor(group) + Q10 + Q8_Q8_1 + Q7_Q7_1 + Q7_Q7_2 , data = df)
summary(mod)
```

```{r}
mod <- lm( log_relational_novelty ~ factor(group) * factor(stage) + Q10 + Q8_Q8_1 + Q7_Q7_1 + Q7_Q7_2 , data = df)
summary(mod)
```

## Nest Phase in Group [ Linear Mixed Model ]

```{r}
# convert to nominal factor
df$user2 = factor(df$user2)
df$stage = factor(df$stage)
df$group = factor(df$group)
```

```{r}
# explore the data and their levels 
library(plyr)
ddply(df, ~ group * stage, function(data) summary(data$log_relational_novelty) )
ddply(df, ~ group * stage, summarise, log_relational_novelty.mean=mean(log_relational_novelty), log_relational_novelty.sd = sd(log_relational_novelty))
```
```{r}
# histograms for two factors
hist(df[df$group == 0 & df$stage == 1,]$log_relational_novelty)
hist(df[df$group == 0 & df$stage == 2,]$log_relational_novelty)
hist(df[df$group == 0 & df$stage == 3,]$log_relational_novelty)
hist(df[df$group == 0 & df$stage == 4,]$log_relational_novelty)
hist(df[df$group == 1 & df$stage == 1,]$log_relational_novelty)
hist(df[df$group == 1 & df$stage == 2,]$log_relational_novelty)
hist(df[df$group == 1 & df$stage == 3,]$log_relational_novelty)
hist(df[df$group == 1 & df$stage == 4,]$log_relational_novelty)
hist(df[df$group == 2 & df$stage == 1,]$log_relational_novelty)
hist(df[df$group == 2 & df$stage == 2,]$log_relational_novelty)
hist(df[df$group == 2 & df$stage == 3,]$log_relational_novelty)
hist(df[df$group == 2 & df$stage == 4,]$log_relational_novelty)
hist(df[df$group == 3 & df$stage == 1,]$log_relational_novelty)
hist(df[df$group == 3 & df$stage == 2,]$log_relational_novelty)
hist(df[df$group == 3 & df$stage == 3,]$log_relational_novelty)
hist(df[df$group == 3 & df$stage == 4,]$log_relational_novelty)
boxplot(log_relational_novelty ~ group * stage, data = df, xlab="Group.Stage", ylab="log_relational_novelty")
with(df, interaction.plot(group, stage, log_relational_novelty, ylim=c(0, max(log_relational_novelty)))) # interaction plot
```
```{r}
# library for LMM we will use on relational novelty 

library(lme4)
library(lmerTest)
library(car)
```

# set sum-to-zero contrasts for the Anova cells 

```{r}
contrasts(df$group) <= "contr.sum"
contrasts(df$stage) <= "contr.sum"
```

```{r}
# stage is nested within group 
fit <- lmer(log_relational_novelty ~ ( group / stage ) +  ( 1 | user2), data = df)
Anova(fit, type=3, test.statistics="F")
summary(fit)
```


```{r}
library("multcomp")
summary(glht(fit, linfct = mcp(group = "Tukey")))
```
```{r}
boxplot(log_relational_novelty ~ group * stage, df)
```
```{r}
model = lmer( log_relational_novelty ~ group + (1 | user2) + ( 1 | stage), data = df, REML = FALSE)
model
```
> Comment: Relational novelty increase when we go from 0, 1, 2, to group 3. 

```{r}
model.null = lmer( log_relational_novelty ~ group + Q7_Q7_2 +  (1 + Q7_Q7_2 | user2) + (1 + Q7_Q7_2 | stage), data = df, REML = FALSE)
model.null
```
```{r}
anova(model.null, model)
```
> Comment -> Model with the mashup skills as covariate is essentially the same as without when stage and subjects are random variables. 


```{r}
full.model = lmer( log_relational_novelty ~ group/stage + + Q7_Q7_1 + Q7_Q7_2 + Q8_Q8_1 + Q10 + (1 + Q7_Q7_1 | user2) + (1 + Q7_Q7_2 | user2) + (1 + Q8_Q8_1 | user2) + (1 + Q10 | user2), data = df, REML = FALSE)
Anova(full.model, type=3, test.statistics="F")
summary(full.model)
```
```{r}
library(performance)

check_collinearity(full.model)

```
```{r}
full.model.2 = lmer( log_relational_novelty ~ group/stage + + Q7_Q7_1 + Q8_Q8_1 + Q10 + (1 + Q7_Q7_1 | user2) + (1 + Q8_Q8_1 | user2) + (1 + Q10 | user2), data = df, REML = FALSE)
full.model.2
```

```{r}
anova(full.model, full.model.2)
```
```{r}
library(car)

vif(full.model)
```
```{r}
vif(full.model.2)
```

